services:
  app:
    image: php:8.2-cli
    container_name: task_manager_api_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: php -S 0.0.0.0:8000 -t public
    networks:
      - task_manager_api_network

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: task_manager_api_mysql
    environment:
      MYSQL_ROOT_PASSWORD: task_manager_root_password
      MYSQL_DATABASE: task_manager_api
      MYSQL_USER: task_manager_user
      MYSQL_PASSWORD: task_manager_password
    ports:
      - "3311:3306"
    volumes:
      - task_manager_api_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - task_manager_api_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    container_name: task_manager_api_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 0
    ports:
      - "8087:80"
    depends_on:
      - mysql
    networks:
      - task_manager_api_network

volumes:
  task_manager_api_mysql_data:

networks:
  task_manager_api_network:
    driver: bridge
