version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: task_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager_api
    ports:
      - "3314:3306"
    networks:
      - task_network

  php:
    image: php:8.2-fpm
    container_name: task_manager_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - database
    networks:
      - task_network
    build:
       context: .
       dockerfile: Dockerfile

  nginx:
    image: nginx:alpine
    container_name: task_manager_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - task_network

networks:
  task_network:
    driver: bridge
